name: astronomy-lab1
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astroid=2.4.2
  - autopep8=1.5.4
  - beautifulsoup4=4.9.3
  - brotlipy=0.7.0
  - ca-certificates=2020.11.8
  - certifi=2020.11.8
  - cffi=1.14.4
  - chardet=3.0.4
  - cryptography=3.2.1
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=67.1
  - idna=2.10
  - isort=5.6.4
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.3
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - loguru=0.5.3
  - lxml=4.6.1
  - lz4-c=1.9.2
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mccabe=0.6.1
  - mypy=0.790
  - mypy_extensions=0.4.3
  - mysql-common=8.0.21
  - mysql-libs=8.0.21
  - ncurses=6.2
  - nspr=4.29
  - nss=3.59
  - numpy=1.19.4
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.4
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.2.4
  - psutil=5.7.3
  - pthread-stubs=0.4
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2020.4
  - qt=5.12.9
  - readline=8.0
  - requests=2.25.0
  - setuptools=49.6.0
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - tzdata=2020d
  - urllib3=1.25.11
  - wheel=0.35.1
  - wrapt=1.11.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - scipy==1.5.4
